[project]
name = "bi-diamond-blm-comrad"
version = "1.0.0"
dependencies = [ "comrad==0.1.3",]
description = "Expert GUI for the BI-DIAMOND-BLM devices."
[[project.maintainers]]
name = "martinja"
email = "javier.martinez.samblas@cern.ch"

[build-system]
requires = [ "comrad==0.1.3",]
build-backend = "comrad_package.builder"

[tool.comrad.package]
entrypoint = "premain.py"
