[project]
name = "diamond-blm-expert-gui"
version = "1.0.4"
dependencies = [ "pyqtgraph==0.10.0.post0", "comrad==0.1.3", "h5py==3.5.0",]
description = "Expert GUI for the BI-DIAMOND-BLM devices."
[[project.maintainers]]
name = "martinja"
email = "javier.martinez.samblas@cern.ch"

[build-system]
requires = [ "comrad==0.1.3",]
build-backend = "comrad_package.builder"

[tool.comrad.package]
entrypoint = "premain.py"
arguments = "--hide-log-console --hide-status-bar -s SPS.USER.ALL"
